package com.example.ccas.retrieval.domain.type;

public enum DecisionReasonCode {
    RELIABLE_VERIFIED_CASE_FOUND,
    NO_RELIABLE_VERIFIED_CASE,
    RELIABLE_CATEGORY_REFERENCE_FOUND,
    NO_RELIABLE_CATEGORY_REFERENCE,
    RELIABLE_OFFICIAL_GUIDE_FOUND,
    NO_RELIABLE_OFFICIAL_GUIDE,
    CATEGORY_MARGIN_TOO_SMALL,
    CASE_CATEGORY_CONFLICT,
    CASE_REFERENCE_CATEGORY_MISMATCH,
    RISK_SIGNAL_PRESENT
}
